name: Run Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: |
        uv sync

    - name: Set up .env for test
      run: |
        echo "API_KEY=${{ secrets.TEST_API_KEY }}" > .env
        echo "ENV=test" >> .env

    - name: Run tests
      run: |
        uv run pytest --cov=app --cov=tests --cov-report=term --cov-report=xml